include: package:flint/analysis_options.flutter.yaml
analyzer:
  plugins:
    - custom_lint
  errors:
    unused_result: ignore

linter:
  rules:
    - use_key_in_widget_constructors
    - require_trailing_commas