name: forui_assets
description: "Assets for Forui"
version: 0.1.0
homepage: https://github.com/forus-labs/forui

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nitrogen_types: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.0
  flint: ^2.8.1
  nitrogen: ^0.1.0

dependency_overrides:
  nitrogen:
    path: ../../cauldron/nitrogen
  nitrogen_types:
    path: ../../cauldron/nitrogen_types

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/icons/

nitrogen:
  use-package: true
  prefix: 'F'
