name: Forui Build Artifact

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - .github/workflows/forui_build_artifact.yaml
      - forui/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-artifact:
    if: github.actor != 'auto-maid[bot]'
    name: Build Forui Artifact
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: forui

    steps:
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.AUTO_MAID_APP_ID }}
          private_key: ${{ secrets.AUTO_MAID_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: subosito/flutter-action@v2.20.0
        with:
          cache: true

      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: dart run ../tool/sort.dart forui
      - run: dart format .

      - uses: EndBug/add-and-commit@v9
        with:
          pull: '--rebase --autostash'
          add: '*'
          new_branch: 'build-artifacts'
          push: 'origin build-artifacts --set-upstream --force'
